version: 0.2

run-as: root

phases:
  install:
    commands:
      # - echo installing RVM
      - echo `whoami`
      # - `cd /home`
      - command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
      - curl -sSL https://get.rvm.io | bash -s stable --ruby
      - curl -sSL https://get.rvm.io | bash -s stable --rails
      - source /usr/local/rvm/scripts/rvm
      - rvm get stable --autolibs=enable
      
      - echo add usergrop rvm
      - usermod -a -G rvm `whoami`
      # - echo run rvm.sh
      # - source /etc/profile.d/rvm.sh
      - rvm version
      - rails --version
      - echo Installing Bundler...
      - gem install bundler
      - bundle exec install
  pre_build:
    commands:
      - rails db:migrate
      - echo Rails installed
      # - cp config/database.yml.example config/database.yml
      # - RAILS_ENV=test bundle exec rake db:setup
      # - RAILS_ENV=test bundle exec rake db:migrate
  build:
    commands:
      - echo Running rspec tests...
      - bundle exec rspec spec/