version: 0.1
phases:
  install:
    commands:
      - echo installing RVM
      - command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
      - command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
      - curl -sSL https://get.rvm.io | bash
      - curl -sSL https://get.rvm.io | bash -s stable --ruby
      - curl -sSL https://get.rvm.io | bash -s stable --rails
      - source /usr/local/rvm/scripts/rvm
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - echo Rails installed
      # - cp config/database.yml.example config/database.yml
      # - RAILS_ENV=test bundle exec rake db:setup
      # - RAILS_ENV=test bundle exec rake db:migrate
  build:
    commands:
      - echo Running rspec tests...
      - bundle exec rspec spec/