version: 0.1
phases:
  install:
    commands:
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - echo Rails installed
      # - cp config/database.yml.example config/database.yml
      # - RAILS_ENV=test bundle exec rake db:setup
      # - RAILS_ENV=test bundle exec rake db:migrate
  build:
    commands:
      - echo Running rspec tests...
      - bundle exec rspec spec/